# Generated by Django 5.1.1 on 2024-09-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contractor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
