# Generated by Django 5.1.1 on 2024-09-29 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('near_miss', 'Near Miss'), ('injury', 'Injury'), ('property_damage', 'Property Damage'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('witnesses', models.ManyToManyField(blank=True, related_name='witnessed_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Incident',
                'verbose_name_plural': 'Work Incidents',
            },
        ),
    ]
